# Generated by Django 5.0.3 on 2024-06-05 14:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_costumer_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Costumer',
        ),
    ]
