# Generated by Django 5.0.3 on 2024-06-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_costumer_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='costumer',
            new_name='customer',
        ),
    ]
